name: vk_plus
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  url_launcher: ^6.1.5
  desktop_webview_window: ^0.1.6
  path_provider: ^2.0.11
  crypto: ^3.0.2
  requests: ^4.4.1
  collapsible_sidebar: ^2.0.2
  sidebarx: ^0.7.0
  easy_sidemenu: ^0.3.1
  flutter_svg: ^1.1.1+1
  flutter_vector_icons: ^1.0.0
  curved_navigation_bar: ^1.0.3
  side_navigation: ^1.0.2
  sidebar_bigeagle: ^0.1.5+2
  desktop: ^3.1.5
  buttons_tabbar: ^1.3.6
  dart_vlc: ^0.3.0
  marquee: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/vk_plus_logo_extended.png
    - assets/images/vk_plus_logo.png
    - assets/images/home.svg


  fonts:
    - family: Gotham
      fonts:
        - asset: assets/fonts/gothampro.ttf
        - asset: assets/fonts/gothampro_black.ttf
